spring:
  config:
    activate:
      on-profile: local

ALLOWED_ORIGINS: "http://localhost:5173"
JWT_EXPIRATION_MS: 3600000
spring:
  config:
    activate:
      on-profile: local

ALLOWED_ORIGINS: "http://localhost:5173"
JWT_EXPIRATION_MS: 3600000

# SOLO PARA LOCAL â€“ NO SUBIR A PROD
B2_KEY_ID: 0054f15815ae2550000000001
B2_APPLICATION_KEY: K0052EHdMmAPD+DYlBe3Fn13m5NHAHg
B2_BUCKET_ID: 14df91f598d185ea9ea20515
B2_BUCKET_NAME: fixa-media