spring:
  application:
    name: fixa-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/turnero?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:change-me-super-secret-change-me-super-secret}
  refresh-secret: ${JWT_REFRESH_SECRET:change-me-refresh-secret-change-me-refresh-secret}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:2592000000}

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: fixa-api

notifications:
  api:
    url: ${NOTIFICATIONS_API_URL:https://beta.notificaciones.fixe.com.ar/api/notifications}
    key: ${APP_API_KEY:}

mercadopago:
  access-token: ${MP_ACCESS_TOKEN:TEST-5097366561977523-122011-f4903541ee4333b78af5aefbf0bf6235-323751961}
  public-key: ${MP_PUBLIC_KEY:TEST-38790462-e990-4cc3-a4b3-3a9ccd60a8f8}
  webhook-secret: ${MP_WEBHOOK_SECRET:ed7961aded85d2c1d2c68c2e147d8e9b80b02781a15912b26f96405ca804d973}
  back-url: ${MP_BACK_URL:https://api.fixe.com.ar/backoffice/suscripcion/ready}
